apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: nginxww
  name: nginxww
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
    nodePort: 30050
  selector:
    run: nginxww
  type: NodePort
status:
  loadBalancer: {}
